name: test
on:
  push:
    branches-ignore:
    - main
jobs:
  ui-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm ci

      - name: Caching nodeJS
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: | 
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
        
      - name: Test Code
        uses: mujo-code/puppeteer-headful@12.3.1
        with:
          args: npm run test-e2e